version: '3.7'

services:
#  indexer:
#    build:
##      args:
##        PLATFORM: ${PLATFORM:-linux/arm64}
#      context: .
#    image: indexer:local
#    ports:
#      - "3030:3030"
#    volumes:
#      - ./.near:/root/.near
#    expose:
#      - 3030
#    env_file:
#      - .env

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env.db


volumes:
  postgres_data:
